/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class magic_powder_Hashtable */

#ifndef _Included_magic_powder_Hashtable
#define _Included_magic_powder_Hashtable
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     magic_powder_Hashtable
 * Method:    hello
 * Signature: (I)I
 */
JNIEXPORT jint JNICALL Java_magic_1powder_Hashtable_hello
  (JNIEnv *, jclass, jint);

/*
 * Class:     magic_powder_Hashtable
 * Method:    makeHashtable
 * Signature: (IIIILjava/lang/String;)J
 */
JNIEXPORT jlong JNICALL Java_magic_1powder_Hashtable_makeHashtable
  (JNIEnv *, jclass, jint, jint, jint, jint, jstring);

/*
 * Class:     magic_powder_Hashtable
 * Method:    mapHashtable
 * Signature: (Ljava/lang/String;)J
 */
JNIEXPORT jlong JNICALL Java_magic_1powder_Hashtable_mapHashtable
  (JNIEnv *, jclass, jstring);

/*
 * Class:     magic_powder_Hashtable
 * Method:    unmapHashtable
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_magic_1powder_Hashtable_unmapHashtable
  (JNIEnv *, jclass, jlong);

/*
 * Class:     magic_powder_Hashtable
 * Method:    insert_bytes
 * Signature: (JLjava/lang/String;[B)V
 */
JNIEXPORT void JNICALL Java_magic_1powder_Hashtable_insert_1bytes
  (JNIEnv *, jclass, jlong, jstring, jbyteArray);

/*
 * Class:     magic_powder_Hashtable
 * Method:    insert_doubles
 * Signature: (JLjava/lang/String;[D)V
 */
JNIEXPORT void JNICALL Java_magic_1powder_Hashtable_insert_1doubles
  (JNIEnv *, jclass, jlong, jstring, jdoubleArray);

/*
 * Class:     magic_powder_Hashtable
 * Method:    get_bytes
 * Signature: (JLjava/lang/String;)[B
 */
JNIEXPORT jbyteArray JNICALL Java_magic_1powder_Hashtable_get_1bytes
  (JNIEnv *, jclass, jlong, jstring);

/*
 * Class:     magic_powder_Hashtable
 * Method:    get_doubles
 * Signature: (JLjava/lang/String;)[D
 */
JNIEXPORT jdoubleArray JNICALL Java_magic_1powder_Hashtable_get_1doubles
  (JNIEnv *, jclass, jlong, jstring);

#ifdef __cplusplus
}
#endif
#endif
